services:
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    command: --config /oauth2-proxy.cfg
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
    restart: unless-stopped
    networks:
      - int-network

  nginx:
    container_name: oauth2-nginx
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - node-app
    networks:
      - int-network

  node-app:
    build: .
    container_name: sample-node-app
    volumes:
      - ./app/index.html:/app/index.html
    environment:
      - NODE_ENV=production
    networks:
      - int-network

networks:
  int-network:
    name: ext_network
    external: true
